In [2]:
import pandas as pd

data = pd.read_csv('../data/AB_comparison.csv')
data

,id,example,annotator,first_question_1_influence_presence,repeated_question_1_influence_presence,first_question_2_techniques,repeated_question_2_techniques,first_question_3_intention_clarity,repeated_question_3_intention_clarity,first_question_4_intention,...,repeated_question_9_reaction,first_question_10_certainty,repeated_question_10_certainty,first_comment,repeated_comment,first_updated_at,repeated_updated_at,first_certainty_level,repeated_certainty_level,annotator_group
0,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",0,Umiarkowanie widoczny,Umiarkowanie widoczny,Autorytet,Autorytet,Intencja słabo widoczna,Intencja umiarkowanie widoczna,Podkreślenie wyjątkowości produktu\nPokazanie ...,...,początkowe ulegnięcie opinii osoby wywierające...,Umiarkowana pewność,Umiarkowana pewność,NaN,NaN,2025-11-17T01:21:30.028871,2025-12-11T23:31:10.882599,3.0,3.0,komunikacja
1,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",8,Dobrze widoczny,Dobrze widoczny,Autorytet\nEfekt „wszyscy to wiedzą”\nEtykieto...,Autorytet\nEtykietowanie\nJesteśmy wyjątkowi,Intencja umiarkowanie widoczna,Intencja dobrze widoczna,zapatrzenie w autorytet\nzachwalenie tego co u...,...,"trudno powiedzieć niby chce ,ale poszuka innyc...",Wysoka pewność,Niska pewność,NaN,NaN,2025-11-13T23:01:49.881366,2025-12-13T19:55:23.466805,4.0,2.0,rodzic
2,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",12,Jednoznaczny,Jednoznaczny,Autorytet\nReguła lubienia,Autorytet,Intencja otwarcie wyrażona,Intencja dobrze widoczna,- (intencja wyrażona przez strategię marketing...,...,- refleksja nad technikami wpływu stosowanymi ...,Wysoka pewność,Wysoka pewność,"- ,,post Nikego'' -powinno być post NIKE albo ...","- post ,,Nike'' a nie ,,Nikego'', nie odmienia...",2025-11-16T13:10:12.097307,2025-12-13T11:27:01.975694,4.0,4.0,psycholog
3,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",17,Trudno ocenić,Umiarkowanie widoczny,Autorytet,Etykietowanie\nPodobieństwa,Trudno ocenić,Intencja umiarkowanie widoczna,to tylko reflekcja,...,"zauważą manipulację, trochę śmieszne, jak łatw...",Niska pewność,Wysoka pewność,NaN,NaN,2025-11-09T20:26:37.655378,2025-12-16T20:25:44.995788,2.0,4.0,nauczyciel
4,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",20,Jednoznaczny,Jednoznaczny,Autorytet,Autorytet,Intencja otwarcie wyrażona,Intencja otwarcie wyrażona,Kupienie butów.,...,"Na początku uległa marketingowi, ale po przemy...",Wysoka pewność,Całkowita pewność,NaN,NaN,2025-11-14T22:29:46.921121,2025-12-15T16:23:31.675059,4.0,5.0,nastolatek
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",0,Brak wpływu,Brak wpływu,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Całkowita pewność,NaN,NaN,2025-11-16T01:35:26.296070,2025-12-11T22:29:50.171227,NaN,5.0,komunikacja
745,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",7,Brak wpływu,Brak wpływu,NaN,NaN,NaN,NaN,NaN,...,NaN,Umiarkowana pewność,NaN,NaN,NaN,2025-11-13T14:08:17.730999,2025-12-16T13:40:21.034518,3.0,NaN,rodzic
746,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",13,Umiarkowanie widoczny,Umiarkowanie widoczny,Humor\nPrzewidywanie żalu,Humor\nOdwoływanie się do lęku\nPrzewidywanie ...,Intencja dobrze widoczna,Intencja umiarkowanie widoczna,zniechęcenie Ani do noszenia matching outfitów...,...,brak reakcji na wypowiedzi Mai,Wysoka pewność,Całkowita pewność,NaN,NaN,2025-11-16T15:48:35.006452,2025-12-11T14:17:41.388129,4.0,5.0,psycholog
747,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",15,Brak wpływu,Słabo widoczny,NaN,Przewidywanie żalu,NaN,Intencja słabo widoczna,NaN,...,"pozostałe osoby nie reagują na to, co Maja mówi",Umiarkowana pewność,Umiarkowana pewność,NaN,NaN,2025-11-09T19:28:20.329902,2025-12-11T18:30:46.288521,3.0,3.0,nauczyciel
748,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",23,Słabo widoczny,Umiarkowanie widoczny,NaN,Odwoływanie się do uczucia miłości,Intencja umiarkowanie widoczna,Intencja dobrze widoczna,"przekonanie, że ""matching outfity"" to głupi po...",...,dopytywanie się o koncepcję matching outfits,Umiarkowana pewność,Umiarkowana pewność,NaN,"troche nie wiem czy to wpływ, czy dawanie opinii",2025-11-16T16:43:49.714256,2025-12-16T18:01:11.016098,3.0,3.0,nastolatek

In [13]:
data['techniques_changed'] = data.apply(
    lambda row: (row['first_question_2_techniques'] != row['repeated_question_2_techniques']) and (row['first_question_2_techniques'] == row['first_question_2_techniques'] or row['repeated_question_2_techniques'] == row['repeated_question_2_techniques']) , axis=1
)

data

,id,example,annotator,first_question_1_influence_presence,repeated_question_1_influence_presence,first_question_2_techniques,repeated_question_2_techniques,first_question_3_intention_clarity,repeated_question_3_intention_clarity,first_question_4_intention,...,first_question_10_certainty,repeated_question_10_certainty,first_comment,repeated_comment,first_updated_at,repeated_updated_at,first_certainty_level,repeated_certainty_level,annotator_group,techniques_changed
0,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",0,Umiarkowanie widoczny,Umiarkowanie widoczny,Autorytet,Autorytet,Intencja słabo widoczna,Intencja umiarkowanie widoczna,Podkreślenie wyjątkowości produktu\nPokazanie ...,...,Umiarkowana pewność,Umiarkowana pewność,NaN,NaN,2025-11-17T01:21:30.028871,2025-12-11T23:31:10.882599,3.0,3.0,komunikacja,False
1,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",8,Dobrze widoczny,Dobrze widoczny,Autorytet\nEfekt „wszyscy to wiedzą”\nEtykieto...,Autorytet\nEtykietowanie\nJesteśmy wyjątkowi,Intencja umiarkowanie widoczna,Intencja dobrze widoczna,zapatrzenie w autorytet\nzachwalenie tego co u...,...,Wysoka pewność,Niska pewność,NaN,NaN,2025-11-13T23:01:49.881366,2025-12-13T19:55:23.466805,4.0,2.0,rodzic,True
2,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",12,Jednoznaczny,Jednoznaczny,Autorytet\nReguła lubienia,Autorytet,Intencja otwarcie wyrażona,Intencja dobrze widoczna,- (intencja wyrażona przez strategię marketing...,...,Wysoka pewność,Wysoka pewność,"- ,,post Nikego'' -powinno być post NIKE albo ...","- post ,,Nike'' a nie ,,Nikego'', nie odmienia...",2025-11-16T13:10:12.097307,2025-12-13T11:27:01.975694,4.0,4.0,psycholog,True
3,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",17,Trudno ocenić,Umiarkowanie widoczny,Autorytet,Etykietowanie\nPodobieństwa,Trudno ocenić,Intencja umiarkowanie widoczna,to tylko reflekcja,...,Niska pewność,Wysoka pewność,NaN,NaN,2025-11-09T20:26:37.655378,2025-12-16T20:25:44.995788,2.0,4.0,nauczyciel,True
4,8,"Siedziałam wieczorem w łóżku, przeglądałam Ins...",20,Jednoznaczny,Jednoznaczny,Autorytet,Autorytet,Intencja otwarcie wyrażona,Intencja otwarcie wyrażona,Kupienie butów.,...,Wysoka pewność,Całkowita pewność,NaN,NaN,2025-11-14T22:29:46.921121,2025-12-15T16:23:31.675059,4.0,5.0,nastolatek,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",0,Brak wpływu,Brak wpływu,NaN,NaN,NaN,NaN,NaN,...,NaN,Całkowita pewność,NaN,NaN,2025-11-16T01:35:26.296070,2025-12-11T22:29:50.171227,NaN,5.0,komunikacja,False
745,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",7,Brak wpływu,Brak wpływu,NaN,NaN,NaN,NaN,NaN,...,Umiarkowana pewność,NaN,NaN,NaN,2025-11-13T14:08:17.730999,2025-12-16T13:40:21.034518,3.0,NaN,rodzic,False
746,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",13,Umiarkowanie widoczny,Umiarkowanie widoczny,Humor\nPrzewidywanie żalu,Humor\nOdwoływanie się do lęku\nPrzewidywanie ...,Intencja dobrze widoczna,Intencja umiarkowanie widoczna,zniechęcenie Ani do noszenia matching outfitów...,...,Wysoka pewność,Całkowita pewność,NaN,NaN,2025-11-16T15:48:35.006452,2025-12-11T14:17:41.388129,4.0,5.0,psycholog,True
747,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",15,Brak wpływu,Słabo widoczny,NaN,Przewidywanie żalu,NaN,Intencja słabo widoczna,NaN,...,Umiarkowana pewność,Umiarkowana pewność,NaN,NaN,2025-11-09T19:28:20.329902,2025-12-11T18:30:46.288521,3.0,3.0,nauczyciel,True
748,1030,"Osoba 1 (Ania, 16 lat, pisze na grupie klasowe...",23,Słabo widoczny,Umiarkowanie widoczny,NaN,Odwoływanie się do uczucia miłości,Intencja umiarkowanie widoczna,Intencja dobrze widoczna,"przekonanie, że ""matching outfity"" to głupi po...",...,Umiarkowana pewność,Umiarkowana pewność,NaN,"troche nie wiem czy to wpływ, czy dawanie opinii",2025-11-16T16:43:49.714256,2025-12-16T18:01:11.016098,3.0,3.0,nastolatek,True

In [14]:
data.groupby('annotator')['techniques_changed'].mean()

annotator
0     0.533333
1     0.766667
2     0.766667
3     0.600000
4     0.566667
5     1.000000
6     0.833333
7     0.766667
8     0.966667
9     0.700000
10    0.700000
11    0.900000
12    0.633333
13    0.933333
14    0.833333
15    0.800000
16    0.666667
17    0.833333
18    0.866667
19    0.700000
20    0.733333
21    0.966667
22    0.827586
23    0.666667
24    1.000000
Name: techniques_changed, dtype: float64